### PR TITLE
irb120: remove roslaunch_check deps.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Avoids a slew of CMake warnings printed during building.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Similar to https://github.com/ros-industrial/abb/pull/167.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: :bellhop_bell:

**Comment by jrgnicho** [comment]
@gavanderhoorn  Could you rebase?

**Comment by gavanderhoorn** [comment]
Done.

**Comment by gavanderhoorn** [comment]
@jrgnicho: Travis seems happy, even after the rebase.

**Review by jrgnicho — APPROVED** [review]

**Comment by jrgnicho** [comment]
@gavanderhoorn thanks

**Pull request merged**
