### PR TITLE
Remove abb_irb120_gazebo package

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
Remove the abb_irb120_gazebo package it is now located in the indigo-devel branch.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn I have created the indigo-devel branch and this pull request removes the abb_irb120_gazebo package from the groovy-devel branch.

**Comment by gavanderhoorn** [comment]
Looks good, but don't forget to remove the additions in `abb_irb120_moveit_config` as well.

**Comment by gavanderhoorn** [comment]
And in `abb_irb120t_moveit_config`. It's `launch/moveit_planning_execution_gazebo.launch` in both.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn: I removed the launch files, is it ready to be merged?

**Comment by gavanderhoorn** [comment]
Think so: does it revert e7a9e988? :)

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn, I undid the changes I made and then reverted the merge for the Introduction of Gazebo simulator support for IRB 120 and now this should remove all of the changes made by e7a9e988.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: can this be merged? If you are waiting on a `+1`, then +1.

**Comment by Levi-Armstrong** [comment]
@gavanderhorn: Thank you for reminding me. I will merge it.

**Pull request merged**
