### PR TITLE
Switch to Github Actions for CI

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Still using `industrial_ci`, but now hosted by Github Actions.

Fairly minimal `matrix` build of Melodic and Noetic on Bionic and Focal. Might add Xenial+Kinetic back later (for Ubuntu ESM).

Runs here: [gavanderhoorn/abb_experimental/actions](https://github.com/gavanderhoorn/abb_experimental/actions).

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
For https://github.com/ros-industrial/ros_industrial_issues/issues/74

**Comment by gavanderhoorn** [comment]
CI is green, runs were successful.

Converting to PR.

**Review by NadiaHG — APPROVED** [review]
I am not a maintainer of this package but, if my opinion counts, I think these changes should be merged.

**Comment by gavanderhoorn** [comment]
Thanks @ipa-nhg :+1:

**Pull request merged**
