### PR TITLE
Add ABB IRB 1600 8/1.45 variant

### PR DESCRIPTION
**Pull request by gonzalocasas**
This PR adds the ABB IRB 1600 8/1.45 variant to the `abb_irb1600_support` package. If I understand it correctly, it is no longer desirable to include the moveit_config package that goes with it, so I have skipped this part.

The difference between this new variant and the existing IRB 1600 is on the link2 and the limits of all joints.

Please let me know if any changes are required.

### CODE REVIEW

**Comment by gonzalocasas** [comment]
A reference moveit config package is available here in case it serves for testing to anyone: https://github.com/gramaziokohler/abb_irb1600_8_145_moveit_config

**Review by gavanderhoorn — CHANGES_REQUESTED** [review]
I've submitted https://github.com/gramaziokohler/abb_experimental/pull/1 to switch to using abb_resources for colour and material definitions.

Other than that, this looks OK to me.

Thanks for the PR :+1: 

(I've not verified the joint limits, but I trust you have)

**Comment by gonzalocasas** [comment]
Thanks!

> (I've not verified the joint limits, but I trust you have)

Yes, I looked them up in the tech specs documentation of ABB for these models.

**Review by gavanderhoorn — APPROVED** [review]
Can't test myself, but @gonzalocasas stated he's tested it, so approving.

**Comment by gavanderhoorn** [comment]
Thanks again @gonzalocasas :+1:

**Comment by gavanderhoorn** [comment]
I'm squash merging this, as my fixup doesn't need to end up in the commit history.

**Pull request merged**
