### PR TITLE
Cleaned up PR 112 (add 20/2.50 and 40/2.55 variants to IRB 4600)

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

This is a cleaned up version of #112, which had too many commits and a very complex commit history.

I've kept provenance on all commits.

Locally tested, seems to be working.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
As this is my "own" PR, I cannot review it any more. Hence the requests to other ros-i reviewers.

If any of you could review, I'll merge.

Note: I've reviewed this PR in its previous version (being #112). All my comments and requests have been addressed already.

**Comment by gavanderhoorn** [comment]
@rtonnaer: could you perhaps also verify whether you're OK with these contributions?

Perhaps @dave992 could take a look as well and verify with the hw?

**Review by dejaniraai — APPROVED** [review]
Changes look good.

**Comment by gavanderhoorn** [comment]
Thanks @dejaniraai. I'll give @rtonnaer and @dave992 some time to respond as well.

**Review by NadiaHG — APPROVED** [review]
LGTM :+1:

**Comment by dave992** [comment]
Looks good! I have just tested it on the hw and everything works as expected.

**Comment by gavanderhoorn** [comment]
Thanks @ipa-nhg and @dave992 for checking.

I'm going to merge this.

**Comment by gavanderhoorn** [comment]
Thanks for all the work @rtonnaer and for iterating :100: 

I'll buy you a :beer: some time.

**Pull request merged**
