### PR TITLE
Support Package for ABB IRB1200 5/90

### PR DESCRIPTION
**Pull request by geoffreychiou**
@Levi-Armstrong

### CODE REVIEW

**Comment by AustinDeric** [comment]
@geoffreychiou please change isnan to std::isnan

**Comment by geoffreychiou** [comment]
@AustinDeric The PR I made is a support package and does not contain any C++ code.

**Comment by Jmeyer1292** [comment]
Can we PLEASE get this merged?

**Comment by Jmeyer1292** [comment]
Thank you! Hallelujah! We merged a new robot.

**Pull request merged**
