### PR TITLE
Fix #14: Corrects tool0 to match controller tool0

### LINKED ISSUE #14: irb120: tool0 does not match the controller tool0

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Just for the sake of repository history: your commit doesn't mention which pkg this is fixing?

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn, this work?

**Comment by gavanderhoorn** [comment]
I know it's difficult, but I think we really should wait with merging PRs until a second pair-of-eyes has +1-ed things.

**Comment by gavanderhoorn** [comment]
But, +1 on this.

**Comment by gavanderhoorn** [comment]
And thanks for fixing up the commit message.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn, Sorry, I am new to this. I took your review as a second pair-of-eyes with the only fix being the commit message, but after your comments I believe I should be waiting for the +1 from another developer. Is this correct?

**Comment by gavanderhoorn** [comment]
No, I am the second pair-of-eyes, but had not +1-ed your fix-up.

Perhaps it was my fault, and I should've been more clear with my initial comment/question.

**Comment by Levi-Armstrong** [comment]
The question I was asking is, should I be waiting for another developer to +1 the pull request before merging?

**Comment by gavanderhoorn** [comment]
You and I are 1+1, so that makes two _pairs of eyes_ (see also [IndustrialPullRequestReview](http://wiki.ros.org/Industrial/Tutorials/IndustrialPullRequestReview)).

**Comment by Levi-Armstrong** [comment]
Thank you, this helps a lot.

On Sun, Mar 1, 2015 at 12:13 PM, G.A. vd. Hoorn notifications@github.com
wrote:

> You and I are 1+1, so that makes two _pairs of eyes_ (see also
> IndustrialPullRequestReview
> http://wiki.ros.org/Industrial/Tutorials/IndustrialPullRequestReview).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-industrial/abb_experimental/pull/16#issuecomment-76621929
> .

## 

Levi Armstrong

**Pull request merged**
