### PR TITLE
How can I connect ABB IRB120 on the RobotStudio

### PR DESCRIPTION
**Pull request by james2254**
After setting parameters，i run the server program，virtual FlexPendant report errors。How can solve this problem？I follow the steps in the ros wiki。The website is http://wiki.ros.org/abb/Tutorials。My robot is ABB IRB120。
image

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Duplicate of #29?

**Comment by shaun-edwards** [comment]
#29 is an issue, this is a PR.  @Levi-Armstrong, the `groovy-devel` branch has gotten ahead of the `indigo-devel` branch.  This PR syncs them (although it may not have been intended to).  Regardless, syncing the branches is something that we should do.  Until this PR is closed, we cannot make a proper PR to do this.

**Comment by gavanderhoorn** [comment]
@shaun-edwards wrote:

> #29 is an issue, this is a PR

Yes, but still: a PR is used here to report an issue. It is the same issue as #29, hence it would seem to be a duplicate.

> the `groovy-devel` branch has gotten ahead of the `indigo-devel` branch.

The only commits that are in `groovy-devel` that are not in `indigo-devel` are an incorrect merge of the Gazebo related changes by @culletom that should have gone into `indigo-devel`, and a revert of that merge by @Levi-Armstrong ([diff](https://github.com/ros-industrial/abb_experimental/compare/groovy-devel)). I don't think it makes sense to merge those into `indigo-devel` ..

**Comment by shaun-edwards** [comment]
@gavanderhoorn, thanks for the clarification...I agree this is a duplicate and should be closed.  @Levi-Armstrong?

**Pull request closed without merging**
