### PR TITLE
Feature/irb6660

### PR DESCRIPTION
**Pull request by wlg1984**
[irb6660_100_330_macro.zip](https://github.com/ros-industrial/abb_experimental/files/2984447/irb6660_100_330_macro.zip)
[irb6660_130_310_macro.zip](https://github.com/ros-industrial/abb_experimental/files/2984448/irb6660_130_310_macro.zip)

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for the PR.

<del>Should this be opened against `ros-industrial/abb` instead? There is already an `abb_irb6600_support` pkg in that repository: [ros-industrial/abb/abb_irb6600_support](https://github.com/ros-industrial/abb/tree/kinetic-devel/abb_irb6600_support).</del> Edit: nvm, missed a `6`.

**Review by gavanderhoorn — CHANGES_REQUESTED** [review]
There are lots of references to `irb_6650s` variants in launch files, the package manifest and other places. That would need to be fixed.

Please take a look at the package manifest of the support pkgs, as the `author` tags are incorrect, as well as the description of the supported series and variants.

**Comment by gavanderhoorn** [comment]
@wlg1984: was this a mistake?

**Comment by wlg1984** [comment]
I have mistakenly created the pull request.

**Pull request closed without merging**
