### PR TITLE
Update travis to use upstream repo

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Review by gavanderhoorn — APPROVED** [review]
Looks like Travis is happy again, so am I.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn, It looks like I cant merge it without an actual approval being added.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Sorry, had to refresh my page.

**Comment by gavanderhoorn** [comment]
I have approved the PR.

Perhaps reload the page?

**Pull request merged**
