### PR TITLE
fix typo in irb1600_6_12_macro.xacro

### PR DESCRIPTION
**Pull request by keerthanamanivannan**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Great. Just waiting for Travis to complete.

**Comment by gavanderhoorn** [comment]
Thanks @keerthanamanivannan 👍.

And thanks for noticing. Seems our Travis (`roslaunch`) tests don't fail on this.

**Comment by keerthanamanivannan** [comment]
haha sure! Thanks for the quick response. It was a super minor typo.

**Comment by gavanderhoorn** [comment]
True, but it does completely mess up the `tool0` orientation.

**Pull request merged**
