### PR TITLE
Add ABB IRB 1200 moveit package

### PR DESCRIPTION
**Pull request by ajshort**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@ajshort Thank you for the contribution. Can you add the components described [here](http://wiki.ros.org/Industrial/Tutorials/Create_a_MoveIt_Pkg_for_an_Industrial_Robot) in the "Update Configuration Files" section?

**Comment by ajshort** [comment]
@Levi-Armstrong Done in a4f67cba720efda20037579e952183da8462e4c8

**Comment by Levi-Armstrong** [comment]
Great Thank you.

**Comment by gavanderhoorn** [comment]
@ajshort: thanks for this. Travis seems to be failing on [some missing files](https://travis-ci.org/ros-industrial/abb_experimental/jobs/278072361#L1116-L1121):

```
FAILURE:
[/root/catkin_ws/src/abb_experimental/abb_irb1200_support/tests/roslaunch_test_irb1200_5_90.xml]:
	while processing /root/catkin_ws/src/abb_experimental/abb_irb1200_support/launch/robot_interface_download_irb1200_5_90.launch:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/root/catkin_ws/src/abb_experimental/abb_irb1200_support/launch/robot_interface_download_irb1200_5_90.launch'
wrote test file to [/root/catkin_ws/build/abb_irb1200_support/test_results/abb_irb1200_support/roslaunch-check_tests_roslaunch_test_irb1200_5_90.xml.xml]
...writing test results to /root/catkin_ws/build/abb_irb1200_support/test_results/abb_irb1200_support/roslaunch-check_tests_roslaunch_test_irb1200_7_70.xml.xml
FAILURE:
[/root/catkin_ws/src/abb_experimental/abb_irb1200_support/tests/roslaunch_test_irb1200_7_70.xml]:
	while processing /root/catkin_ws/src/abb_experimental/abb_irb1200_support/launch/robot_interface_download_irb1200_7_70.launch:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/root/catkin_ws/src/abb_experimental/abb_irb1200_support/launch/robot_interface_download_irb1200_7_70.launch'
wrote test file to [/root/catkin_ws/build/abb_irb1200_support/test_results/abb_irb1200_support/roslaunch-check_tests_roslaunch_test_irb1200_7_70.xml.xml]
```

For `robot_interface_download_irb1200_5_90.launch` I'm not sure what is going on, but the `7_70` launch file is indeed not there in the support package.

Is the PR missing files?

**Comment by gavanderhoorn** [comment]
Ah, you renamed the file in c3b9ce518851525bc2094116358a9ec71a2525b5 (removed the variant suffix). Was that on purpose?

It may seem redundant, but we like to be as explicit as possible with all of this, that's why all files that are variant-specific have a variant suffix (ie: `_5_90` and `_7_70`).

**Comment by ajshort** [comment]
Yep, I removed the suffix as the same file can be used for both variants. Hopefully I have pushed a fix - will see how the tests go.

**Comment by gavanderhoorn** [comment]
@ajshort wrote:
> Yep, I removed the suffix as the same file can be used for both variants. Hopefully I have pushed a fix - will see how the tests go.

Ok. As I wrote above, it may seem redundant, but we like to be as explicit about things as possible. Additionally, at the moment these files may all look the same, but that may change in the future. This way we already have the infrastructure in place, and everything (ie: support for different variants) is as independent as it can be.

**Comment by stwirth** [comment]
+1 for merging this. @gavanderhoorn did you want the both robot variants not to share the `joint_names.yaml`?  I think it is fine as the variants only differ in size and not number of joints.

**Comment by gavanderhoorn** [comment]
@stwirth wrote:
> +1 for merging this. @gavanderhoorn did you want the both robot variants not to share the `joint_names.yaml`?  I think it is fine as the variants only differ in size and not number of joints.

None of the files should be shared by variants, with the exception of meshes (geometry).

As I wrote above in an earlier comment: the files may contain the same information right now, but that is not guaranteed to stay that way, and by giving each variant its own fileset, we keep them as decoupled as possible.

**Comment by stwirth** [comment]
@gavanderhoorn understood. I made a new PR to fix this: #81.

**Comment by gavanderhoorn** [comment]
Closing this one, but continuing (commits have been included in) #85.

**Pull request closed without merging**
