### PR TITLE
Transfer IRB4400 Support Package

### PR DESCRIPTION
**Pull request by Jmeyer1292**
Removes the 4400 package from this repo.

See [this](https://github.com/ros-industrial/abb/pull/131) for the associated `abb` PR.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
We should also update the [package manifest](https://github.com/ros-industrial/abb_experimental/blob/446bf69d487fc8f50904e0c45632e4c3bcf4a39e/abb_experimental/package.xml) of the metapackage to no longer include this one.

**Comment by Jmeyer1292** [comment]
Updated. Also removed a non existent move it config package.

**Comment by gavanderhoorn** [comment]
@Jmeyer1292 wrote:
> Also removed a non existent move it config package.

yes, I accidently added that (I had one to test the IRB4400 support pkg).

**Comment by Jmeyer1292** [comment]
Good to go?

**Pull request merged**
